platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
- name: source-code

outputs:
- name: build-output

run:
  path: source-code/ci/tasks/build.sh

caches:
- path: maven